name: fetch
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  # Supabase
  supabase_flutter: ^2.8.1
  supabase: ^2.6.0

  # Hive local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # config keys
  flutter_dotenv: ^5.1.0

  # Icons
  hugeicons: ^0.0.7
  animated_icon: ^0.0.9
  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.8
  fluentui_system_icons: ^1.1.266

  #State Manager 
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1


  #Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0


  # Utils
  intl: ^0.18.0
  either_dart: ^1.0.0


  # Device Manager
  device_info_plus: ^11.1.1

  # Adaptive UI
  flutter_screenutil: ^5.9.3

  # Theme
  flex_color_scheme: ^8.0.1

  # Svg
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1

  # Animation
  lottie: ^3.1.3
  pulsator: ^1.0.0+2
  animate_do: ^3.3.4
  animations: ^2.0.11
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  circular_rotation: ^0.0.2


  # Notification
  flutter_local_notifications: ^18.0.1

  # Modal Bottom Sheet
  modal_bottom_sheet: ^3.0.0
  flutter_popup: ^3.3.0
  geolocator: ^13.0.2
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  another_flushbar: ^1.12.30
  dio: ^5.7.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

# Assets
  assets:
    - assets/keys/
    - assets/animated/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/tunes/
    - assets/svgs/

# Fonts with name

  fonts:
    - family: DM_Sans
      fonts:
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans-Thin.ttf
          weight: 300
